#35568 Zero warnings
postsharp/PostSharp.Engineering pull request #97
Opened 2024-11-08 11:49 UTC by svick

2024-11-25 13:07 UTC, prochan2 requested changes

2024-11-25 13:07 UTC, prochan2 commented on Directory.Build.props
> +        <NoWarn>$(NoWarn);NU1903;NU1904</NoWarn>
Comment on what these warnings mean, why they are suppressed, and when (if ever) this suppression should be removed.

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/Build/Model/ArtifactPublisher.cs
> +            var files1 = new List<FilePatternMatch>();
```suggestion
            var matchedFiles = new List<FilePatternMatch>();
```

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/Build/Model/ArtifactPublisher.cs
> -        public Tester[] Testers { get; init; } = [];
This has to stay public. See Metalama.Try, for example.

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/Build/Model/Product.cs
> +                                switch ( tester.Execute( context, directories.Private, buildInfo, settings.Dry ) )
CHECK

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/ContinuousIntegration/TeamCityCreateProjectCommandSettings.cs
> +[PublicAPI]
[UsedImplicitly] should be user for *CommandSettings as the reason for them being public is that the Sprectre.Console instantiates them.

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/Dependencies/Model/BuildOrderHelper.cs
> -    public static void SetBuildOrder( params DependencyDefinition[] orderedProducts )
CHECK

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/Git/GitBulkRenameCommand.cs
> +        public override int Execute( [System.Diagnostics.CodeAnalysis.NotNull] CommandContext context, [System.Diagnostics.CodeAnalysis.NotNull] GitBulkRenameSettings settings )
Why?

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/NuGet/RenamePackagesCommand.cs
> +        private static bool Execute( ConsoleHelper console, RenamePackageCommandSettings settings )
This is used in Metalama Compiler's engineering.

2024-11-25 13:07 UTC, prochan2 commented on src/PostSharp.Engineering.BuildTools/Utilities/DotNetTool.cs
> +        public static DotNetTool Resharper { get; } = new( "jb", "JetBrains.Resharper.GlobalTools", "2024.2.7", "jb" );
Add a comment on why this version is chosen / why it cannot be upgraded.

2024-11-28 17:41 UTC, svick commented on src/PostSharp.Engineering.BuildTools/Utilities/DotNetTool.cs
> +        public static DotNetTool Resharper { get; } = new( "jb", "JetBrains.Resharper.GlobalTools", "2024.2.7", "jb" );
I think this was the highest version when I made this change.
Should I upgrade to the newer one?

2024-12-05 09:18 UTC, prochan2 approved these changes

2024-12-05 16:34 UTC, merged